AWSTemplateFormatVersion: "2010-09-09"

Description: Github Actions Conf

Resources:
  GithubActionsOIDCProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList: 
        - sts.amazonaws.com
      Url: https://token.actions.githubusercontent.com
  ChillguireGitHubActionsAssumeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: !Sub
        - |
          {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Effect": "Allow",
                    "Principal": {
                        "Federated": "${OIDCARN}"
                    },
                    "Action": "sts:AssumeRoleWithWebIdentity",
                    "Condition": {
                        "StringEquals": {
                            "${OIDCName}:aud": "sts.amazonaws.com"
                        },
                        "StringLike": {
                            "${OIDCName}:sub": "repo:chillguire/*"
                        }
                    }
                }
            ]
          }
        - OIDCARN: !Ref GithubActionsOIDCProvider
          OIDCName: !Select [1, !Split ['/', !Ref GithubActionsOIDCProvider]]
      Policies: 
        - PolicyName: ChillguireGitHubActions-Cloudformation
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              # https://github.com/aws-actions/aws-cloudformation-github-deploy?tab=readme-ov-file#permissions
              - cloudformation:CreateStack
              - cloudformation:DescribeStacks
              - cloudformation:CreateChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:ExecuteChangeSet
              # Project specific
              - ec2:DescribeImages
              - ec2:RunInstances
              - ec2:DescribeInstances
              - ec2:CreateTags
              - lambda:CreateFunction
              - lambda:GetFunction
              - logs:CreateLogGroup
              - logs:DescribeLogGroups
              - logs:PutRetentionPolicy
              - iam:GetRole
              - iam:CreateRole
              - iam:PutRolePolicy
              - iam:PassRole
              - cognito-identity:CreateIdentityPool
              - cognito-identity:SetIdentityPoolRoles
              Resource: "*"
            - Effect: Allow
              Action: ssm:GetParameters
              Resource: arn:aws:ssm:us-east-1:*:parameter/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64
      RoleName: ChillguireGitHubActions-AssumeRoleWithActions